### ISSUE TITLE
adopt to aiohttp 3

### ISSUE THREAD

**Issue by asvetlov** [python/bedevere#100]
The library has changed testing API.
The bot uses non-public attributes, that's why tests fail.

I could find a time for working on issue on next week if nobody will pickup the task first

**Comment by brettcannon** [comment]
I assume you're referencing #99 ?

**Comment by asvetlov** [comment]
Yes, exactly

**Comment by brettcannon** [comment]
Look forward to your PR since I will probably be writing a GH bot at work next week and I want to do it right 😄

**Comment by asvetlov** [comment]
Fixed by #101

**Comment by Mariatta** [comment]
Thanks!

**Comment by asvetlov** [comment]
Sure!
