### ISSUE TITLE
Automatically add type labels

### ISSUE THREAD

**Issue by csabella** [python/bedevere#106]
The labels for `type-documentation` and `type-tests` could automatically be added to pull requests based on the types of files included.  For example, `type-documentation` would contain all `.rst` files, while `type-tests` would contain all files that start with `test_` (except for the blurb).  It may not catch all the changes for documentation and tests, but it would identify some, making triage of pull requests a bit easier.  The other types (bugfix or enhancement) might be able to be retrieved from the bpo.

I started working on this, but I ran into a question.  Currently `check_news` reads through the files to look for the blurb.  Since I plan on looking at all the file names as well, I was wondering if the code to get all the files from the PR should be moved to a level above `check_news` and the new function.  

For example in new `files.py`:
``` python
@router.register('pull_request', action='opened')
async def file_checks(event, gh, *args, **kwargs):
    pr_number = event.data['number']
    filelist = get_files_from_PR(number)
    await check_news(filelist)
    await check_type(filelist)
```

instead of retrieving the files twice:
```  python
@router.register('pull_request', action='opened')
async def check_news(event, gh, *args, **kwargs):
    pr_number = event.data['number']
    files_url = f'/repos/python/cpython/pulls/{pr_number}/files'
    async for file_data in gh.getiter(files_url):
        filename = file_data['filename']
        etc

@router.register('pull_request', action='opened')
async def check_type(event, gh, *args, **kwargs):
    pr_number = event.data['number']
    files_url = f'/repos/python/cpython/pulls/{pr_number}/files'
    async for file_data in gh.getiter(files_url):
        filename = file_data['filename']
        etc
```
I don't know what the pitfalls would be of trying to get all the files upfront, especially with this comment in check_news.
```
    # Could have collected all the filenames in an async set comprehension,
    # but doing it this way potentially minimizes the number of API calls.
```

**Comment by brettcannon** [comment]
Factoring the code out is no problem. As for the comment, that's just me being perpetually paranoid about our quota. 😄

**Comment by Mariatta** [comment]
Closed in https://github.com/python/bedevere/pull/108
