### ISSUE TITLE
Automatically remove all "awaiting" tags when closing/merging a PR

### ISSUE THREAD

**Issue by andresdelfino** [python/bedevere#113]
I have some closed/merged PRs that have one of the "awaiting" on them, and I guess it's common to forget to remove tags. I believe these are unnecessary entries that clutter the view when you people filter the list.

I thought they could be automatically removed when a PR is closed/merged. They aren't useful anymore, right?

If this is deemed useful, I could make a PR.

**Comment by andresdelfino** [comment]
This might be useless, as I just noticed all the PRs are shown in an "Open" tab :stuck_out_tongue:

**Comment by terryjreedy** [comment]
I believe that Awaiting usually is auto-removed when a PR is merged.  Please posts links to examples where this did not occur.  Removing when closed would be a nuisance if the closure is temporary to re-trigger CI bots.

**Comment by andresdelfino** [comment]
Here are all my closed/merged PRs with "awaiting" labels:

https://github.com/python/cpython/pull/7769
https://github.com/python/cpython/pull/7741
https://github.com/python/cpython/pull/7728
https://github.com/python/cpython/pull/7694
https://github.com/python/cpython/pull/7673
https://github.com/python/cpython/pull/7608
https://github.com/python/cpython/pull/7586
https://github.com/python/cpython/pull/7538
https://github.com/python/cpython/pull/7535
https://github.com/python/cpython/pull/6821
https://github.com/python/cpython/pull/6697
https://github.com/python/cpython/pull/6603

I didn't know there were temporary closures :P

As I said in my second comment, the proposed behaviour may be useless.

**Comment by Mariatta** [comment]
All "awaiting ..." labels should have been removed when the PR is merged (done in https://github.com/python/bedevere/pull/58).

On purpose the "awaiting ..." label isn't removed the PR get closed, and not merged. Sometimes we need to close and re-open a PR for various reasons (mistakenly pressed "close and comment", or needing to retrigger the CI). By leaving the labels, at least we can continue the stage it was in, if we decide to reopen the PR. But maybe we need to re-evaluate that. I simply didn't do any research on the PR re-opened PR workflow :)

Consider a scenario where a PR has been approved by a core dev, and it has "awaiting merge" label.
If we accidentally close it, and  the "awaiting merge" label was removed, can the bot re-add the label if we decide to re-open? If GitHub did not wipe the "approved" state after it was re-opened, perhaps the bot will add the label accordingly anyway?

I just searched for merged PRs with any "awaiting ..." label. There really shouldn't be any, but:

[merged and awaiting change review](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Amerged+label%3A%22awaiting+change+review%22) no result
[merged and awaiting changes](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Amerged+label%3A%22awaiting+changes%22) no result
[merged and awaiting core review](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Amerged+label%3A%22awaiting+core+review%22) 1 result
[merged and awaiting merge](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Amerged+label%3A%22awaiting+merge%22) no result
[merged and awaiting review](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Amerged+label%3A%22awaiting+review%22) 1 result

I will look into why those aren't removed.

**Comment by Mariatta** [comment]
@andresdelfino One thing you can do add additional test cases.

https://github.com/python/bedevere/blob/7bc79be974d02b3a202ee42b8d8b6c82ba285b9a/tests/test_stage.py#L545
We tested that "awaiting merge" label gets removed after the PR is merged. There was no test for the other "awaiting ..." labels. 
We should add additional test cases that other "awaiting ..." labels are removed too.

**Comment by andresdelfino** [comment]
I definitely see the advantages of the current behaviour now that you mention this.

Sure, I'll work on that :) Thanks for mentioning it!

**Comment by Mariatta** [comment]
> merged and awaiting core review 1 result
> merged and awaiting review 1 result

I've manually removed those labels.
