### ISSUE TITLE
backport check fails for Python 2.7 fix that's not a backport

### ISSUE THREAD

**Issue by encukou** [python/bedevere#124]
https://github.com/python/cpython/pull/8449 is a fix for a bug that doesn't appear in Python 3. There's no corresponding PR for master. But, Bedevere's [backport check](https://github.com/python/bedevere/blob/master/bedevere/backport.py#L72) sees a PR for a maintenance branch, and insists that there should be a `(GH-XXX)` note in the title.

I didn't find guidance for this specific case in the devguide, but I think the correct thing to do is to merge without the `(GH-XXX)` note, ignoring the status check.

**Comment by encukou** [comment]
I just noticed this is already being discussed in https://github.com/python/core-workflow/issues/211

**Comment by terryjreedy** [comment]
I just added python/core-workflow#278, suggesting a 'skip backport' label for this situation.

**Comment by Mariatta** [comment]
This status check is optional so you can still merge the PR.

I think for now I'll just drop the check for `(GH-NNNN)`, and only checking for `[X.Y]`, so we don't need a new label.
