### ISSUE TITLE
Check-news status: check that the news file is not empty.

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#127]
In https://github.com/python/cpython/pull/8857, they created an empty news file (to make the status pass?) :woman_shrugging: 
I think it is possible to check for the content of the file, and ensure it is not empty, before posting the success status.

**Comment by terryjreedy** [comment]
After Cheryl Sabella had some experience, I asked her to include news files with her patches even though I would edit before pushing.  Blank was fine.  The reason for me was that it is much easier, when near ready to commit, to edit an existing file with the web editor than to push a new file.

However, I see the danger that a commit could be made without the edit.  If a check is added, a minimum of, say, 30 characters, might be reasonable.
