### ISSUE TITLE
Have bedevere remove "needs backport to *" labels

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#13]
Proposed in https://github.com/python/core-workflow/issues/58#issuecomment-298961610 

Since @brettcannon said this can be a bedevere thing, I opened this issue :)

When a PR is created, bedevere can check if [X.Y] is in the PR title, and then apply `cherry-pick for X.Y` label.

1. backports created with cherry_picker.py have [X.Y] for sure
2. those not using cherry_picker.py have been instructed to do that in the devguide
3. even when the cherry-picking bot is in place, I suppose it will also provide [X.Y] as the PR title. This might simplify the cherry-picking bot to just do the cherry-pick and PR creation, and not worry about applying labels. 
4. (non core-dev) contributors can still use cherry_picker.py and the labels still get applied without coredev's intervention.
5. Backports created using cherry_picker.py will also have the link to the original GitHub PR, (GH-XXX in the title/desc), bedevere can remove the `needs backport to [X.Y]` label from the original PR (I think)

**Comment by Mariatta** [comment]
If we decide not to apply cherry-pick labels anymore, then bedevere can just be responsible in removing the `needs backport to X.Y` labels.

**Comment by brettcannon** [comment]
I'm not sure how you would go from cherry-pick back to the original (if a bot were making the cherry-pick PRs then it already has a reference to the original PR). Search through all closed PRs for a matching title? Maybe there's something in the PR data from GitHub but I don't know what it would be off the top of my head.

**Comment by Mariatta** [comment]
Sure, I guess it will be easier to get cherry-picker the bot to do it :) 

Supposedly, there's the reference to the original GitHub issue number in the backport PR.
For example, this backport PR https://github.com/python/cpython/pull/1446, the PR title includes GH-1372, which is the original PR # that was against the master branch. 

Here's another example, https://github.com/python/cpython/pull/1475, #1451 in the PR title is the original PR number.

**Comment by brettcannon** [comment]
Yeah, if there's no metadata in the webhook event in the opening of a cherry-pick PR we can try and guess the original PR by the title.

**Comment by brettcannon** [comment]
One thing to watch out for when reading the title is there is a length limit. This can lead to issues like the title spilling over into the body of the PR message, e.g. https://api.github.com/repos/python/cpython/pulls/1522/ .

**Comment by Mariatta** [comment]
Awesome! Thanks!

**Comment by Mariatta** [comment]
Hmm.. did not work with this PR https://github.com/python/cpython/pull/2253


Which is a backport for https://github.com/python/cpython/pull/1685

**Comment by brettcannon** [comment]
I'll have a look.

**Comment by brettcannon** [comment]
And it works!
