### ISSUE TITLE
Add 'awaiting reviews' with 'CLA not signed'

### ISSUE THREAD

**Issue by matrixise** [python/bedevere#135]
Hi,

You can check with this PR, `the-knights-who-say-hi` add the label `CLA not signed` but after, bedevere add `awaiting review`. 

Normally, the `bedevere` should only add `awaiting review` if the CLA is signed. Is it right?

https://github.com/python/cpython/pull/9840

**Comment by brettcannon** [comment]
The bots run independent of each other so there is no checking of each other's labels.
