### ISSUE TITLE
Automatically hyperlinking of `bpo-` text sometimes causes confusion

### ISSUE THREAD

**Issue by tirkarthi** [python/bedevere#136]
Automatically changing bpo-DDDD to a link to bugs.python.org was introduced in #121 . It's a useful feature but there are a few cases where the PR was raised with wrong title format and while specifying the correct format and the bot rewrites bpo number in the text as a link causing confusion. It does rewriting without notification and thus the comments are silently overwritten unless OP re-reads it.

Example : While commenting the correct format in https://github.com/python/cpython/pull/9906#issuecomment-430177012 bedevere changed `bpo-34996: Add name parameter to proccess and thread pool` to `[bpo-34996](https://bugs.python.org/issue34996): Add name parameter to proccess and thread pool` . The user was confused and changed the PR title with URL. Using backticks also doesn't stop the bot. Is there a way to specify bpo-DDDD without adding hyperlinks in the comments? Maybe this can be skipped in the backticks?

Another example where spaces have to be used to stop rewriting : https://github.com/python/cpython/pull/9755#issuecomment-430679326

Thanks

**Comment by terryjreedy** [comment]
These seem like rather isolated incidents to me.  For 9906, the comment should have been much more specific. "In the title, change 'pbo' to 'bpo'.  A core developer would (I hope) have just made the change, but I am guessing that you currently cannot .  For 9755, the new contributor put the bpo number in the commit message, where it should not be, instead of in the title, where it belongs and where it is left alone.

But I agree that Bedevere should not rewrite inside backticks, as used in 9755.
(Since the PR numbers are already link above, I left '#' off  to avoid adding backlink noise to the PRs. )

**Comment by danishprakash** [comment]
I guess it would be suitable if the bot wouldn't auto-expand links in inline code blocks and mutliline code blocks. That should do the job. Are you working on this @tirkarthi?

**Comment by tirkarthi** [comment]
@danishprakash No, I am not working on this.

@terryjreedy Yes, I can see the feature being useful but it's just that it can be avoided inside the backticks. But it's just a suggestion though based on the two PRs and I am okay if this is not implemented.

Thanks

**Comment by ned-deily** [comment]
@terryjreedy I'm also confused by your comment.  The problem in 9755 had nothing to do with the original contributor's PR; it's that the bot incorrectly altered the comments that Carol and I made.

**Comment by storymode7** [comment]
If nobody's working on it, I'd love to fix this.

**Comment by danishprakash** [comment]
@storymode7 we're still discussing the possible way to go forward with this. As discussed in the other thread, It's preferred to have the bot leave code blocks untouched. I'm working on this but a solid decision from the core members is what's required before I submit any patch.

**Comment by storymode7** [comment]
@danishprakash sure. Let me know if I can be of any help.

**Comment by hugovk** [comment]
Here's another example of the bot breaking marked-up code:

https://github.com/python/cpython/pull/10021#issuecomment-435434983

**Comment by Mariatta** [comment]
Autolinking is now supported by GitHub and I've enabled it in CPython.

Still working on removing the autolink in bedevere.
Related issue: https://github.com/python/core-workflow/issues/361

**Comment by pradyunsg** [comment]
Closing this since bpo isn't actively being used and we'd switched to GitHub's auto-linking anyway. :)
