### ISSUE TITLE
Validate the bpo number

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#15]
The bpo number provided in https://github.com/python/cpython/pull/1798 is not valid (46895)
 https://bugs.python.org/issue46895 is a 404

Maybe bedevere can also validate whether the issue number is correct :)

**Comment by brettcannon** [comment]
Yeah, we could do a simple GET request and see if the response is a 404 or not to flag the issue number as formatted properly but not an actual issue number.

**Comment by serhiy-storchaka** [comment]
Doing a HEAD request may be enough.

**Comment by lysnikolaou** [comment]
Is this issue resolved or should it be implemented? If so, I would be happy to take it up.

**Comment by lysnikolaou** [comment]
This should be closed since #159 is now merged.
