### ISSUE TITLE
Bot breaks existing links that contain bpo numbers

### ISSUE THREAD

**Issue by GPHemsley** [python/bedevere#164]
If the text of a Markdown link contains a mention of a bpo issue, the bot will replace that mention with an embedded link, breaking the syntax, and there is no way to stop it from happening.

The bot should not try to edit existing link text.

Example:
https://github.com/python/cpython/pull/5046#issuecomment-483065260

**Comment by brettcannon** [comment]
Happy to review a PR to make the bot smart enough to not rewrite preexisting links!
