### ISSUE TITLE
Magic comments for labels

### ISSUE THREAD

**Issue by jdemeyer** [python/bedevere#175]
Since labels are pretty important for a CPython PR, it annoys me that ordinary users like me cannot add them. And as far as I know, it's not possible to give people permission to add labels without actually giving them write access.

Since bedevere can read comments and can apply labels, we could use this to allow for special comments to apply labels. For example, the comment `please skip news` (or anything more creative) could be interpreted to add the `skip news` label. Same for `skip issue` and the `needs backport` labels. For `skip news`, I initially reported this on https://github.com/python/blurb_it/issues/37 but maybe it's easier to do with bedevere.

**Comment by brettcannon** [comment]
GitHub has in beta the [triage permission](https://help.github.com/en/articles/repository-permission-levels-for-an-organization) for this exact scenario of allowing people to change labels but not accept PRs, so that's our plan long-term for solving this.

**Comment by Mariatta** [comment]
Last week I've filed a request to GitHub to enable the triage permission to CPython. No reply yet.

**Comment by jdemeyer** [comment]
> GitHub has in beta the [triage permission](https://help.github.com/en/articles/repository-permission-levels-for-an-organization) for this exact scenario of allowing people to change labels but not accept PRs, so that's our plan long-term for solving this.

It doesn't really solve the problem because:

1. Allowing to add arbitrary labels might be dangerous, since you don't want untrusted people to add the `automerge` label for example.
2. Because of 1, you can't give triage permission too easily, so you're just shifting the problem from non-core developers to non-triage-permission developers.

**Comment by Mariatta** [comment]
The plan is to adjust the bot to not listen to automerge if it wasn't added by core-dev. Related discussion https://discuss.python.org/t/proposal-create-bug-triage-team-on-github/992 

Current bpo also allows any issue creator to assign any label they want, leaving it to core devs and triagers to re-adjust labels, so I don't feel like this is a "new" problem to us.

**Comment by terryjreedy** [comment]
The main plus of letting issue creators adjust headers is that we can ask them to close an issue.  I presume they can do the same with PRs.  The main minus is that they can re-open an issue when we (coredevs) have closed it.  Letting them set others is pretty much a wash, as they often set them wrong.
