### ISSUE TITLE
Automatically add 'Backport to xxx' labels based on the affected versions in bpo

### ISSUE THREAD

**Issue by maxking** [python/bedevere#179]
This is just an idea which I think might be helpful for some core devs. I know that the information in bpo might be outdated depending on the age of the ticket, but could be helpful in some situations.

**Comment by lysnikolaou** [comment]
This was already implemented by Mariatta in #174.

**Comment by zware** [comment]
#174 automatically adds *new* "backport" labels when a new branch is opened; I believe @maxking is requesting that the "backport" labels be *applied* to PRs based on the "versions" field of the linked bpo issue.

**Comment by Mariatta** [comment]
We can't do this because bpo is not sending us webhook event when the ticket/version got updated.

**Comment by Mariatta** [comment]
I also have an alternative idea https://github.com/python/core-workflow/issues/267

**Comment by lysnikolaou** [comment]
@zware Thanks for the explanation. I guess, I didn't take enough time to understand what was being proposed. Sorry.

**Comment by maxking** [comment]
Sorry for not being clear in the issue, I meant exactly what Zachary said. Thanks Mariatta for the exaplanation, I'll close this for now.

Also, @Mariatta I guess core-workflow is the right place for such issues/requests in future?

**Comment by brettcannon** [comment]
@maxking correct. Only stuff directly pertaining to the bot should be placed here. All other discussions go to core-workflow.
