### ISSUE TITLE
bpo numbers not always recognized

### ISSUE THREAD

**Issue by freddrake** [python/bedevere#191]
For example:
https://github.com/python/cpython/pull/16331

The bpo number is in the issue title, but was added in an edit.  If there's a way to get bedevere to re-examine a PR, I'm not sure what it is, and I didn't see it in the linked portion of the devguide.

**Comment by brettcannon** [comment]
This was brought up at https://discuss.python.org/t/issue-number-check-not-work/2381/5 and there is support for detecting edits in titles and it's existed for quite a while:

https://github.com/python/bedevere/blob/74cc40bb1fe369f469b18fa6114a3629bab63681/bedevere/bpo.py#L54-L59

There's a separate bug I think that's triggering this problem.
