### ISSUE TITLE
Easter Egg Vids are Unavailable

### ISSUE THREAD

**Issue by hharutyunyan** [python/bedevere#201]
The videos for the Easter Egg 1 (soft cushions) and Easter Egg 2 (comfy chair), as well as the video for Fun Thanks (Spanish Inquisition),  are made unavailable on YouTube, while the bot still puts the those in comments.
Probably, the links should be replaced by available ones or should be removed.

**Comment by brettcannon** [comment]
@hharutyunyan this keeps happening, so I think it might be time to just remove the links. Do you want to propose a PR to do that?

**Comment by hharutyunyan** [comment]
> @hharutyunyan this keeps happening, so I think it might be time to just remove the links. Do you want to propose a PR to do that?

@brettcannon ok agreed. I’ll propose one later today.
