### ISSUE TITLE
Changing labels when a review gets requested

### ISSUE THREAD

**Issue by lysnikolaou** [python/bedevere#219]
While working on python/cpython#19694, I found out that labels don't change, if a PR has been approved and the author requests a review once more.

I think it would be a good idea to change the label back to `awaiting core review`, when a review gets requested. Thoughts?

**Comment by brettcannon** [comment]
Seems reasonable. I know @vstinner has been worried about changes made post-approval when auto-merge is turned on. Maybe it's worth resetting the reviews as well?

**Comment by Mariatta** [comment]
Related issue: https://github.com/python/core-workflow/issues/325

**Comment by Mariatta** [comment]
This has been addressed in #220. Thanks.
