### ISSUE TITLE
Dependabot for bedevere is using requirements.in instead of requirements.txt

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#226]
I was wondering why dependabot did not bump the sentry-sdk update for bedevere. When I logged in to dependabot, it appears that it checked bedevere's requirements.in instead of requirements.txt. 

![Screen Shot 2020-06-19 at 10 01 25 AM](https://user-images.githubusercontent.com/5844587/85161241-54cc8100-b214-11ea-8a6f-b5c53cfdcaf1.png)

requirements.in has not been updated for the past 3 years. Perhaps we should remove it.

I could not find any documentation on how to tell dependabot to look at requirements.txt instead of requirements.in

**Comment by brettcannon** [comment]
@Mariatta controlling Dependabot can be done via a config file: https://help.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates
