### ISSUE TITLE
Use a "skip issue" label for skipping the issue number check

### ISSUE THREAD

**Issue by brettcannon** [python/bedevere#25]
This is instead of a "trivial" label to give finer-grained control over what is (or is not) important when other checks are added that should also be conditionally skipped.

See https://mail.python.org/pipermail/python-dev/2017-June/148486.html

**Comment by brettcannon** [comment]
To transition, the `skip issue` label should be created and applied to all issues with the `trivial` label. Then the change to Bedevere can be made. Once it's verified as live, the `trivial` label can be deleted.

**Comment by Mariatta** [comment]
Should there be two labels: `skip issue` and `skip news entry`? 
That was my understanding from the thread....

**Comment by brettcannon** [comment]
Yes, there should be eventually. But since #22 isn't committed yet there's no need for a `skip news` label yet.

**Comment by Mariatta** [comment]
Got it. Thanks for the clarification :)
🤔  Instead of creating a new label, can we rename the existing `trivial` label into `skip issue`?

**Comment by brettcannon** [comment]
@Mariatta yes, but there would be a race condition between renaming the issue and deploying a new version of Bedevere that recognizes `skip issue`. And since labels have no ID beyond their text there's no reason I can think of to rename it but potentially have some new PR come in that is labeled as failing due to its lack of issue number.

**Comment by Mariatta** [comment]
So here are the PRs with "trivial" label: 257 total, only 5 of them open
https://github.com/python/cpython/pulls?utf8=%E2%9C%93&q=is%3Apr%20label%3Atrivial%20

When a label is renamed, all of the affected PRs and issues get updated with the new label. 
I think it will be less effort to rename the label instead of creating a new one and try to apply the new label.

However.. I don't know what can be done to avoid the said race condition 😅

**Comment by brettcannon** [comment]
Adding a new label to all of the open PRs is about 6 clicks from https://github.com/python/cpython/pulls :

1. Click the Labels button
2. Click Trivial
3. Click the "Select All" box
4. Click Labels drop-down
5. Click "skip issue"
6. Click off of drop-down to apply

And then label deletion is about 3 clicks from there. Hopefully this doesn't come off as pedantic or anything as it isn't meant to; I just want to show that I have thought about this probably too much and I'm confident that it works without much extra work compared to a rename where there's an ever so slight race condition while Heroku updates 😉 .

**Comment by brettcannon** [comment]
All done! Thanks for the PR!
