### ISSUE TITLE
Copy over labels to backport PRs

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#26]
When backporting, I try to copy over labels from the original PR to the backport PR, for example the "trivial" or "documentation" labels.

Perhaps this is something that can be automated and done by bedevere.
At the very least, the "trivial" label should be copied over.

UPDATE:
Copy over `skip issue` label instead of `trivial`. `trivial` label is no more.

UPDATE 2.0:
At the very least, copy over `skip issue` and `skip news` labels.

**Comment by brettcannon** [comment]
It can definitely be automated, although the "trivial" label will probably be renamed shortly thanks to #25 .

**Comment by terryjreedy** [comment]
Now it would be Skip issue and Skip news, and copying them would be nice.

**Comment by Mariatta** [comment]
@miss-islington does not have write access to CPython repo, so it can't copy over the labels.
This has to be done by @bedevere-bot.

**Comment by Mariatta** [comment]
These labels should not be copied over to the backport PR:
- needs backport to X.Y
- CLA signed / CLA not signed
- awaiting ...

**Comment by brettcannon** [comment]
Does anything other than the "skip" labels need to be copied? A safe list would probably be better than a block list in this instance.

**Comment by Mariatta** [comment]
Hmm.. I like copying the other labels like `type-documentation` or `sprint` too, but those are not necessary, and I might be the only one doing that ...
If no-one else care enough about the other labels, then only copying the `skip ... ` labels sounds good to me :)

**Comment by brettcannon** [comment]
We can also copy those, I'm just saying we shouldn't make a list of what _not_ to copy, but instead of what _should_ be copied. So far there's

* skip ...
* type...
* sprint

Anything else?

**Comment by terryjreedy** [comment]
With a safe set, new labels are not copied until we decide they should be.

**Comment by brettcannon** [comment]
@terryjreedy correct.

**Comment by brettcannon** [comment]
I've started work on fixing this. Hopefully I can complete it next week.
