### ISSUE TITLE
Move the PR back to awaiting review if review was dismissed

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#269]
In https://github.com/python/cpython/pull/22253#pullrequestreview-488290678, I approved the PR but later decided to retract my review.

I think in this situation the PR should be moved back to "awaiting review" state.

**Comment by DanielNoord** [comment]
Implementation in https://github.com/python/bedevere/pull/490 😄

**Comment by DanielNoord** [comment]
@Mariatta Gentle ping for a review of #490. Not sure if this is appreciated but since this affects `awaiting merge` labels I can imagine this could be more problematic than some of (my) other open PRs.
