### ISSUE TITLE
Automatically set skip news and skip issue label to dependabot PRs

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#287]
We added the config to update GitHub actions dependencies monthly on CPython repo. https://github.com/python/cpython/pull/22787

One thing that would help is to automatically add the `skip news` and `skip news` labels to those PRs.

Example dependabot PR https://github.com/python/cpython/pull/22919

**Comment by Mariatta** [comment]
We may also need to automatically add the "needs backport to X.Y" label. 🤔

**Comment by hugovk** [comment]
You should be able to have dependabot add labels itself via config: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#labels

**Comment by Mariatta** [comment]
Thanks for the tip! Like this? https://github.com/python/cpython/pull/22927

**Comment by hugovk** [comment]
Looks good!
