### ISSUE TITLE
Regenerate bedevere's access token

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#328]
I received email about this change: 
https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

I have updated the token for miss-islington. We need to do it for bedevere, but I don't have access to bedevere's account.

Todo:
- [x] Regenerate the access token for bedevere (by going to Settings > Personal Access Token). The token will look like `ghp_.....`
- [x] Set the new access token to bedevere's Heroku app
- [x] Delete the old access token (once confirmed that the new token is working)

**Comment by brettcannon** [comment]
@Mariatta I updated the token in Heroku. I will give it a day to see if anything breaks before I delete the old token.

I'm also happy to give you access to the GH account. If you want it just let me know.
