### ISSUE TITLE
Still link to b.p.o when both issue number and trivial label are found

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#4]
For example: https://github.com/python/cpython/pull/1120

It has both bpo-NNNN in the PR title and `trivial` label.
bedevere status check should still have details link to the said issue.

Thanks :)

**Comment by terryjreedy** [comment]
Definitely.  In this case, the issue https://bugs.python.org/issue29861 and initial patch were not at all trivial, just the minor cleanup for occasional test failures reported on the issue.
