### ISSUE TITLE
Bedevere does not see new news file

### ISSUE THREAD

**Issue by terryjreedy** [python/bedevere#42]
When I updated https://github.com/python/cpython/pull/2573, a bedevere/news 'No news entry' comment appeared, with a red X.  I created one with blurb and pushed again -- see the end of
https://github.com/python/cpython/pull/2573/files#diff-3b70d006c35749af8a303582e5346202
However, bedevere did not recheck and is now wrong after 20 minutes.

**Comment by brettcannon** [comment]
A certain someone changed the filename format in blurb from what was originally agreed upon in our spec without telling me. 😉 Fix is coming as soon as testing and code coverage come back green.

**Comment by terryjreedy** [comment]
Fix seems to have worked.  Thanks.
