### ISSUE TITLE
Restore support for `bpo-*` issue numbers in PR titles

### ISSUE THREAD

**Issue by ezio-melotti** [python/bedevere#426]
https://github.com/python/cpython/pull/91439 failed with
![20220412--01-8](https://user-images.githubusercontent.com/25624924/162955583-9e4de4d6-b48f-4af7-8fa6-6705d3234a08.png)
 
It seems that after #420 bedevere only looks for GH numbers:
https://github.com/python/bedevere/blob/cd97d6be08485937d36d8ca055879efd510161e9/bedevere/gh_issue.py#L12-L29

This should be updated to try GH first, and fallback on bpo if a GH number is missing (assuming something is done with the id and the distinction matters, otherwise a single check is enough).

While we are at it, should it also be case-insensitive or do we want to enforce lowercase `gh-*`?

cc @Mariatta, @brettcannon

**Comment by brettcannon** [comment]
You should be able to just tweak the regex and update the tests.

P.S. I announced a while back I was stepping down from heading up infrastructure stuff, so I'm not the best person to be cc'ing to get stuff done. 😉
