### ISSUE TITLE
Add link to the GitHub Issue from the PR

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#428]
We used to automatically append a link to the bpo ticket from the GitHub PR, by looking at the PR title's issue number.

In https://github.com/python/bedevere/pull/420, the functionality was dropped. I had thought that GitHub UI would automatically link the issue number when referenced like this, however this is not a case. GitHub would automatically link the issue in the PR descriptions or in the PR comments, but not in the title.

To make it easier for us to navigate to the issue from the title, we should add back the reference to the issue in the PR description.
Upon seeing the `GH-` issue number in the PR title, bedevere should edit the description and add the issue number there.
We don't need to add it as a link, because GitHub can automatically render `gh-` as links, so just adding the text `gh-NNNN` at the end would be sufficient.

This text should be added only if the issue number has not already mentioned, to avoid duplicated links.

**Comment by ryanlong1004** [comment]
@Mariatta there is code than already handles this in gh_issue.py.  Is this issue still valid?

**Comment by Mariatta** [comment]
We only create status checks in `gh_issue.py`. Basically we need to add back this logic:
https://github.com/python/bedevere/blob/6f4978e1649168c3e4516647d0bdf08e05812afa/bedevere/bpo.py#L42-L47

It was removed in PR #420 when we removed `bpo.py` and added `gh_issue.py`

**Comment by Mariatta** [comment]
So yes this issue is still valid.
