### ISSUE TITLE
Inaccurate message about needing news entry.

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#439]
The comment by bedevere says "Every change to Python requires a news entry".
But most trivial changes like typo fixes don't.

I wonder if we can reword it, but I also don't have good suggestion on a better wording here.

**Comment by AlexWaygood** [comment]
The current message is:

> Every change to Python [requires a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
>
> Please, add it using the [blurb_it](https://blurb-it.herokuapp.com/) Web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

Maybe we could change this to:

> Most significant changes to Python [require a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
>
> Add a NEWS entry using the [blurb_it](https://blurb-it.herokuapp.com/) Web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

**Comment by AlexWaygood** [comment]
Or maybe:

> Check [the CPython Developer's Guide](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python) to see whether your PR is likely to require a NEWS entry.
> 
> Add a NEWS entry using the [blurb_it](https://blurb-it.herokuapp.com/) Web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

**Comment by hugovk** [comment]
The [relevant and linked devguide section](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python) begins:

> Almost all changes made to the code base deserve an entry in `Misc/NEWS.d`.

Before detailing the exceptions.

We could mirror this language. It would help link Bedevere's comment to the relevant bit of the devguide.

For example:

> Almost every change to Python [requires a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
> 
> Please add it using the [blurb_it](https://blurb-it.herokuapp.com/) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

Or:

> Almost all changes to Python [requires a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
> 
> Please add it using the [blurb_it](https://blurb-it.herokuapp.com/) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

**Comment by ezio-melotti** [comment]
> Almost every change to Python [requires a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
> 
>   Please add it using the [blurb_it](https://blurb-it.herokuapp.com/) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

I like this.

A minor nitpick is that "Please add it" is unconditional, probably because the original message said "Every change".

Maybe another option could be:
> If your change requires a NEWS entry [requires a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python) (most changes do),
> please add it using the [blurb_it](https://blurb-it.herokuapp.com/) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

Or simply:

> Almost every change to Python [requires a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
> You can add one using the [blurb_it](https://blurb-it.herokuapp.com/) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

**Comment by ethanfurman** [comment]
I like the last option; it states the premise, and how to take any needed action .

**Comment by AlexWaygood** [comment]
"Almost every change" is objectively correct, but not subjectively correct. This message is only shown to first-time contributors, and they are disproportionately likely to be contributing one-line typo fixes (or similarly trivial docs fixes). I worry that "almost every change requires a news entry" might still lead to lots of new contributors adding unnecessary news entries for that kind of PR.

**Comment by JelleZijlstra** [comment]
I'm not sure it's even objectively correct. skip-news PRs are pretty common: https://github.com/python/cpython/pulls?q=is%3Aopen+is%3Apr+label%3A%22skip+news%22

**Comment by ezio-melotti** [comment]
`s/Almost every change/Most changes/`?
Or "Changes to Python generally require..." (possibly preceded by a "Non-trivial").

**Comment by hugovk** [comment]
I've updated the wording in PR https://github.com/python/bedevere/pull/447 to use "Most changes..."

It would be good to get something merged, because the current wording is causing extra work in needless additions (and deletions), for example https://github.com/python/cpython/pull/92397.
