### ISSUE TITLE
Run Codecov with the right version

### ISSUE THREAD

**Issue by ezio-melotti** [python/bedevere#462]
It seems that for every PR, codecov is run 16 times:
* 2 times because the workflow is triggered by both `push` and `pull_request` (#461 fixes that)
* 4 times for each workflow because the tests are run with 4 different Python versions
* 2 times for each check
  * first it''s run with `pytest` in the "Run tests" step
  * then it's run on its own in the "Run codecov/codecov-action@v2" step

I think that during the `pytest` step the specified Python version is used, whereas in the `codecov` step the same default version is used for all runs.  This can be seen e.g. in https://github.com/python/bedevere/runs/6655983357 where it fails during the `pytest` step but it succeeds in the `codecov` step.  Because of this, it is not possible to see where the failure is (see #463).

There are three improvements that can be made:
1. the `codecov` step should use the same python version used by the `pytest` step
2. if possible the results created by `pytest` should be reused without running codecov again
3. possibly upload the `xml` report created by pytest as an artifact

**Comment by hugovk** [comment]
This isn't completely accurate, there's a few things with similar names doing different jobs here.

[pytest](https://docs.pytest.org/) is running the tests using the [pytest-cov](https://pytest-cov.readthedocs.io) plugin, which hooks up the [Coverage.py](https://coverage.readthedocs.io/) tool that does the instrumentation and measuring.

[Codecov](https://about.codecov.io/) is a website and doesn't instrument or measure coverage, instead existing coverage results are uploaded and it helps track coverage changes over time, report back for PRs, and provide a UI for exploring coverage for runs.

* Each job runs the tests with pytest once, which measures the coverage once.
* Each job uploads the coverage results to Codecov once.
* The Codecov website combines these all together for each PR.

So:

> There are three improvements that can be made:
> 
> 1. the `codecov` step should use the same python version used by the `pytest` step

The Codecov https://github.com/codecov/codecov-action isn't using Python, it uses Node.js (but it's just uploading data so doesn't really matter. It used to be a bash script.)

> 2. if possible the results created by `pytest` should be reused without running codecov again

pytest/pytest-cov/Coverage.py create the results, Codecov uploads them.

> 3. possibly upload the `xml` report created by pytest as an artifact

Can do, although it might be more useful to generate and upload `html` reports if we want to see them for individual Python versions.

And/or we could use Codecov for this, it's possible to add flags for each Python version in the matrix, and Codecov adds a filter box at the top right for each file. For example:

* https://github.com/python-pillow/Pillow/blob/8bffead4739c1a496025f0935caae1c76b1d4667/.github/workflows/test.yml#L107
* https://app.codecov.io/gh/python-pillow/Pillow/blob/8bffead4739c1a496025f0935caae1c76b1d4667/src/PIL/ImageShow.py

**Comment by ezio-melotti** [comment]
Thanks for clarifying!

> pytest/pytest-cov/Coverage.py create the results, Codecov uploads them.

I thought Codecov ran the coverage tests again and that it was successful because it used a different version of Python instead of using 3.11.  However it was successful not because the coverage check passed during the step (since that was performed in the previous step), but because the upload of the xml report created by `pytest` was successful.  The whole issue was based on a wrong assumption, and is therefore invalid.

> And/or we could use Codecov for this, it's possible to add flags for each Python version in the matrix, and Codecov adds a filter box at the top right for each file. 

This actually added to my confusion and confirmed my assumption -- since I was not able to find the report for 3.11 (or any failure), I thought that it never ran/uploaded the 3.11 report.  Is it accessible at all from the Codecov website or does it need flagging?  If so, it would be nice to add flags as you suggested.

**Comment by hugovk** [comment]
> This actually added to my confusion and confirmed my assumption -- since I was not able to find the report for 3.11 (or any failure), I thought that it never ran/uploaded the 3.11 report. Is it accessible at all from the Codecov website or does it need flagging? If so, it would be nice to add flags as you suggested.

Unfortunately it's not shown as an individual report on Codecov.

PR https://github.com/python/bedevere/pull/464 adds flags, and has an example of how you can filter by version.

https://app.codecov.io/gh/hugovk/bedevere/blob/300b7d0ed649e9535c59db9824e9d1b041080839/bedevere/stage.py

A downside: you do have to be in the file view before filtering to a 3.11 report.

The overview aggregates all reports:

https://codecov.io/gh/hugovk/bedevere/tree/300b7d0ed649e9535c59db9824e9d1b041080839/bedevere

PR https://github.com/python/bedevere/pull/464 also adds `--cov-report term` to print out the summary in the CI run too, so that helps know which files to check.

We could generate the individual HTML reports for each version on the CI, and upload those as artifacts, if you think that would be useful?
