### ISSUE TITLE
Add tox or other test orchestrator to run tests locally

### ISSUE THREAD

**Issue by jaraco** [python/bedevere#469]
Today, I started to run the tests on this project only to learn that there's no orchestration for running the tests. The user is required to know the magical setup to run the tests or manually replicate the [steps used by ci](https://github.com/python/bedevere/blob/ad03d53e210b9c2f84733ef8f264e6831b062e40/.github/workflows/ci.yml#L27-L47). I'd prefer if there were a one-command guide on how to run the tests for the project.

It looks like there is a one-liner that works to run the tests:

```
pip-run -q -r dev-requirements.txt -- -m pytest
```

Of course, it depends on pip-run. Most Python developers are more familiar with something like tox or nox.

Any reason this project doesn't provide such a thing? If it provides, it, I'd also recommend to run the tests using such an orchestrator (to have one primary workflow and not divergent workflows in CI).

**Comment by hugovk** [comment]
Good idea! tox or nox would be great. I have a slight preference to tox because I'm more familiar with it, probably also true with Python developers in general.

> Any reason this project doesn't provide such a thing?

Probably because no-one has contributed one yet :)

>  If it provides, it, I'd also recommend to run the tests using such an orchestrator (to have one primary workflow and not divergent workflows in CI).

Agreed, and it means the CI also effectively tests the orchestrator is working properly too.
