### ISSUE TITLE
Backport PR labels not deleted

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#50]
In https://github.com/python/cpython/pull/3114, the backport labels were not automatically removed by bedevere-bot.

The backport PRs were initially created without `[X.Y]` prefix in PR title.
After the title has been edited, the backport PR labels were still not removed.

This happened in https://github.com/python/cpython/pull/1804 too, where I ended up removing the label myself.

Just curious if this is because the title was edited afterwards, or is there another reason of why bedevere couldn't detect the backport PRs?

Thanks.

**Comment by brettcannon** [comment]
It's because it was edited after the PR was created. When I added that feature I only hooked it up for PR creation:
https://github.com/python/bedevere/blob/3df65d992e3a418342bdfe674a77f89947d03d27/bedevere/backport.py#L18-L19
