### ISSUE TITLE
Bedevere too often misses 'skip news'

### ISSUE THREAD

**Issue by terryjreedy** [python/bedevere#59]
#3635 I had to add [skip news] twice to get bedevere to recognize it.  For the backport #3637, thrice.  This is common with [skip news] and a nuisance.  Can bedevere be made more 'attentive'?  Can a 'check again' button be added?  Can clicking _details_ be made to recheck?

**Comment by Mariatta** [comment]
Sounds like a similar issue where @the-knights-who-say-ni sometimes doesn't apply any CLA check status. This might be issue with GitHub not delivering the webhook.

**Comment by brettcannon** [comment]
Are you waiting several minutes or hours and nothing is happening, @terryjreedy ? Do realize there is an explicit one second delay built in to deal with eventual consistency issues that GitHub has, on top of any delay that may occur from GitHub delivering the event to the bot in a delayed fashion so it will never be instantaneous.

As for Bedevere being "attentive", it's as attentive as it can be as it's entirely based on webhooks being pushed by GitHub to the bot. There is no polling going on here so there's no specific way for us to notice things any faster. Basically if GitHub doesn't tell us the label was added then the bot won't notice. I checked the delivery logs from GitHub and there was only one failure in the past 3 days, so either there's a bug in Bedevere or GitHub simply didn't delivery the webhook event.

Anyway, I can't diagnose this as Bedevere's log don't go that far back and crawling through the hundreds of events that have been delivered to Bedevere to find the set of events that you came up against is going to be a lot of work that I don't have time to do. If this does happen again then leave a comment here and/or email me and I will try to catch it in the logs to see exactly what happened.

**Comment by terryjreedy** [comment]
I am aware that there can be a natural delay.  Next occurrence, I will wait longer and keep track of the times.

**Comment by brettcannon** [comment]
Thanks!

**Comment by igalic** [comment]
as for #61, the file was present, but the date format was incomplete.
if the Bot had reporting on its failure modes, it could be a lot more useful!

**Comment by brettcannon** [comment]
#57 is tracking the plan to improve the failure message

**Comment by brettcannon** [comment]
Has this issue come up lately?

**Comment by brettcannon** [comment]
Since this doesn't seem to have occurred again over the past month I'm closing this with the assumption that it was a GitHub hiccup.
