### ISSUE TITLE
Update NEWS message

### ISSUE THREAD

**Issue by zooba** [python/bedevere#590]
The current NEWS message reads like this:

```
Most changes to Python [require a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).

Please add it using the [blurb_it](https://blurb-it.herokuapp.com/) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.
```

I see many contributors then add a NEWS entry on PRs where they don't need it. This is understandable, but it would be nice if the message could suggest something like "If this change has little impact on Python users, you can wait for a maintainer to confirm that a NEWS entry is required. Maintainers are able to bypass this check."

That would likely help out contributors [like this one](https://github.com/python/cpython/pull/110566) where the NEWS entry is unnecessary but the PR checks are failing _because_ the contributor added an entry. Rather than have them stress out about learning enough ReST syntax, it would be nice if they were given permission to wait for us to tell them whether it's necessary or not.

**Comment by ezio-melotti** [comment]
To be fair the message already links to the devguide, which should explain when a message is needed and when not.

We can still tweak the wording to make it more obvious that they should follow the link if they are not sure -- something like: "If you are not sure whether your PR needs a news entry, check the devguide." or "Most PRs need a NEWS entry.  Check the devguide to see if yours does."

**Comment by zooba** [comment]
The check can only be skipped when a committer or triager adds the label though, so I think it's okay to let them just wait. It's not a big effort to say that we think something needs a NEWS entry (and often we'll suggest what it should say, which can save a review step).
