### ISSUE TITLE
Treat InternalDocs/* like Docs/*?

### ISSUE THREAD

**Issue by skirpichev** [python/bedevere#656]
I.e. add label "docs" (or similar), "skip news", etc.

An example: https://github.com/python/cpython/pull/127687

**Comment by hugovk** [comment]
Good idea, would you like to open a PR?

**Comment by skirpichev** [comment]
Should I use same "docs" label or a new one?

**Comment by hugovk** [comment]
Yes, let's use the same "docs" label.

**Comment by skirpichev** [comment]
PR is ready: https://github.com/python/bedevere/pull/657
