### ISSUE TITLE
bedevere did not remove `needs backport` label

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#95]
PR https://github.com/python/cpython/pull/5500 is a backport for https://github.com/python/cpython/pull/5265

Bedevere should have removed the needs backport PR from https://github.com/python/cpython/pull/5265.

**Comment by Mariatta** [comment]
So it was because the PR title starts with a space: 
```
"title": " [3.6] bpo-32614: Modify re examples to use a raw string to prevent wa…  …rning (GH-5265)"
```
The regex pattern in https://github.com/python/bedevere/blob/master/bedevere/backport.py#L11 did not handle that 😅

**Comment by Mariatta** [comment]
Another example: https://github.com/python/cpython/pull/5037 is the backport for https://github.com/python/cpython/pull/5034. Labels not removed from https://github.com/python/cpython/pull/5034

**Comment by Mariatta** [comment]
Another example from today: https://github.com/python/cpython/pull/5746 is the backport for https://github.com/python/cpython/pull/5726

**Comment by Mariatta** [comment]
For python/cpython#5746, it was because the commit message on python/cpython#5726 was wrong: it did not have the correct bpo- and GH- numbers.

**Comment by Mariatta** [comment]
Another instance where backport pr was not linked correctly:
https://github.com/python/cpython/pull/6807

**Comment by brettcannon** [comment]
It looks like https://github.com/python/bedevere/blob/b41fe6bfc887b1c8156ba1eca2be5d6195801eb3/bedevere/backport.py#L11 is too strict. I bet we can change it to:
```python
TITLE_RE = re.compile(r'\s*\[(?P<branch>\d+\.\d+)\].+\(?:GH-|#)(?P<pr>\d+)\)')
```
It will fix this. This will:
1. Not care about leading whitespace (`\s*`)
1. Always match on the last set of parentheses (`.+`)
1. Require it be `(GH-` or `(#` (`(?:GH-|#)`)
