### ISSUE TITLE
500 errors for the issue number status check

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#97]
Saw 500 errors in the webhooks for several PRs: 
https://github.com/python/cpython/pull/5748
https://github.com/python/cpython/pull/5746
https://github.com/python/cpython/pull/5747

**Comment by Mariatta** [comment]
This is because the PR does not contain bpo- number, so bedevere then looks for the `skip issue` label, but that doesn't exist either, so it doesn't know what to do. 🤔

**Comment by Mariatta** [comment]
This PR could be affected by the same bug https://github.com/python/cpython/pull/5753
It is a PR targeting 2.7 branch, but there was no master PR.
bedevere did not append the bpo- number as a footer.

**Comment by brettcannon** [comment]
Bedevere should set a failing status check when there is no bpo # or `skip issue` label.

**Comment by merwok** [comment]
The thing is that the PR contained `bpo-1234`, but in the commit message for the squashed commit I wrote old-style `#1234` out of habit and aesthetic sense.

**Comment by arhadthedev** [comment]
Is the issue still relevant?
