### ISSUE TITLE
Nosy PR participants in bpo issue

### ISSUE THREAD

**Issue by zhangyangyu** [python/bedevere#98]
I wonder whether it's possible or a good idea to automatically add pull request participants to bpo issue nosy list. Sometimes PR authors or reviewers don't add themselves to bpo issue nosy list and then might lose some notifications happened in bpo.

**Comment by Mariatta** [comment]
Such change is to be done in bugs.python.org side, and it can be reported in http://psf.upfronthosting.co.za/roundup/meta/
cc  @ezio-melotti and @soltysh

I'm ok with adding PR author and reviewers to bpo nosy list.
